// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU-iQ0q-MkGz8gQ9x9E522waoRMWOBAiE',
    appId: '1:997057825862:web:9703ecfbfe4a542b4b4e47',
    messagingSenderId: '997057825862',
    projectId: 'sentidos-de5c4',
    authDomain: 'sentidos-de5c4.firebaseapp.com',
    storageBucket: 'sentidos-de5c4.firebasestorage.app',
    measurementId: 'G-XFR9B2XNB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yfbszQ1TxFtk6BfjjQ9oA1V1GvgV3WU',
    appId: '1:997057825862:android:3392acc4fa021b254b4e47',
    messagingSenderId: '997057825862',
    projectId: 'sentidos-de5c4',
    storageBucket: 'sentidos-de5c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9SVCuLFx_oKQ_R8hI1ym17uPREcKNPqY',
    appId: '1:997057825862:ios:68bd763b6b51b2b74b4e47',
    messagingSenderId: '997057825862',
    projectId: 'sentidos-de5c4',
    storageBucket: 'sentidos-de5c4.firebasestorage.app',
    iosBundleId: 'com.example.aromatizacionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9SVCuLFx_oKQ_R8hI1ym17uPREcKNPqY',
    appId: '1:997057825862:ios:68bd763b6b51b2b74b4e47',
    messagingSenderId: '997057825862',
    projectId: 'sentidos-de5c4',
    storageBucket: 'sentidos-de5c4.firebasestorage.app',
    iosBundleId: 'com.example.aromatizacionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU-iQ0q-MkGz8gQ9x9E522waoRMWOBAiE',
    appId: '1:997057825862:web:6c0da073f23ac9284b4e47',
    messagingSenderId: '997057825862',
    projectId: 'sentidos-de5c4',
    authDomain: 'sentidos-de5c4.firebaseapp.com',
    storageBucket: 'sentidos-de5c4.firebasestorage.app',
    measurementId: 'G-K4ZHQPXHY4',
  );
}
